apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: crossplane
type: Opaque
stringData:
  credentials: |
    {
      "token": "toto",
      "owner": "instadeep-vbr"
    }
  url: "https://dataplane.webhook.domain"
---
apiVersion: github.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: github-secret
      namespace: crossplane
      key: credentials
---
apiVersion: webhook.upbound.io/v1alpha1
kind: Webhook
metadata:
  annotations:
    meta.upbound.io/example-id: webhook/v1alpha1/webhook
  labels:
    testing.upbound.io/example-name: web
  name: aichor-demo
spec:
  forProvider:
    active: false
    configuration:
      - contentType: form
        insecureSsl: false
        secretSecretRef:
          key: credentials
          name: github-secret
          namespace: crossplane
        urlSecretRef:
          key: url
          name: github-secret
          namespace: crossplane
    events:
    - commit_comment
    repository: aichor-demo
